#!/bin/bash

set -ueo pipefail

namespace=rstms_ansible
collection=vmware
version=$(cat VERSION)
tarball="${namespace}-${collection}-${version}.tar.gz"

clean() {
    [ -d docs ] && rm -rf docs
    mkdir docs
    chmod 0700 docs
}

docs() {
    clean
    antsibull-docs sphinx-init --use-current --squash-hierarchy "${namespace}.${collection}" --dest-dir docs
    [ -f "$tarball" ] || wget "https://github.com/${org}/${repo}/releases/download/v${version}/${tarball}"
    (
	cd docs
	pip install -r requirements.txt
	ansible-galaxy collection install --force --upgrade "../$tarball"
	sed -i -e 's|rsync.*|cp -rp temp-rst/* rst/\nrm -rf tmp-rst|' build.sh
	./build.sh
    )
}

usage() {
    echo >&2 "usage: $(basename $0) clean|docs"
    exit 1
}

(( $#>0 )) || usage

case $1 in 
    clean) clean;;
    docs) docs;;
    *) usage;;
esac
