#!/bin/bash
set -ueo pipefail
namespace=rstms_ansible
collection=vmware
org=rstms-ansible
repo="$collection"
version=$(cat VERSION)
[ -d docs ] && rm -rf docs
mkdir docs
chmod 0700 docs
(( $#>0 )) && [[ $1 = clean ]] && exit 0
antsibull-docs sphinx-init --use-current --squash-hierarchy "${namespace}.${collection}" --dest-dir docs
# fix silly use of rsync
sed -e 's|rsync.*|cp -rp temp-rst/* rst/\nrm -rf tmp-rst|' docs/build.sh
tarball="${namespace}-${collection}-${version}.tar.gz"
[ -f "$tarball" ] || wget "https://github.com/${org}/${repo}/releases/download/v${version}/${tarball}"
cd docs
pip install -r requirements.txt
ansible-galaxy collection install --force --upgrade "../$tarball"
./build.sh
