#!/bin/bash
set -ueo pipefail
namespace=rstms_ansible
collection=vmware
version=$(cat VERSION)
[ -d docs ] && rm -rf docs
mkdir docs
chmod 0700 docs
(( $#>0 )) && [[ $1 = clean ]] && exit 0
antsibull-docs sphinx-init --use-current --squash-hierarchy "${namespace}.${collection}" --dest-dir docs
cd docs
pip install -r requirements.txt
ansible-galaxy collection install --force --upgrade "../${namespace}-${collection}-${version}.tar.gz"
./build.sh
