#!/bin/bash
bump
version=$(cat VERSION)
make docs
git push 
ansible-galaxy collection publish --token $(ANSIBLE_GALAXY_TOKEN) $(tarball)
gh release create "v$version" --target master --title "v${version} '$(wonderwords -wpadjective)-$(wonderwords -wpnoun)'" --generate-notes
gh release upload "v$version" rstms_ansible-vmware-${version}.tar.gz
