argument_specs:
  main:
    short_description: vmware workstation instance management role
    description:
      - This role will create or destroy a VM instance based on the `vm_state` variable.
      - When an instance is created, it boots from a netboot ISO downloaded from
        the netboot server which reference the IPXE script for the specified OS.
      - Additionally, an autoconfig response file is generated, as well as an initial
        package tarball.  
      - The role waits for the installation to report completion (or a timeout) then
        cleans up the generated config files on the netboot and autoinstall servers.
    author:
      - Matt Krueger
    options:
      vm_state:
        type: "str"
        required: false
        default: "present"
        description: 
          - "present - create and netboot an instance"
          - "absent - destroy an instance"
      vm_hostname:
        type: "str"
        required: false
        default: "inventory_hostname_short"
        description: "instance name"
      vm_username:
        type: "str"
        required: false
        default: "ansible_user"
        description: "username created on instance during configuration"
      vm_password:
        type: "str"
        required: false
        default: "ansible_become_password"
        description: "password used when creating vm_username account"
      vm_sshd_enabled:
        type: "bool"
        required: false
        default: true
        description: "enable sshd during instance configuration"
      vm_ssh_public_key:
        type: "str"
        required: false
        default: "ansible_user's ~/.ssh/id_ed25519.pub"
        description: "public key configured in vm_username's authorized_hosts file"

#vm_timezone: "{{ lookup('pipe', 'date +%Z') }}"
#vm_cpu_count: 1
#vm_disk_mb: 8192
#vm_ram_mb: 1024
#vm_headless: true
#vm_password_length: 32
#vm_filesystem_dir: false
#
#vm_update_known_hosts: true
#vm_secrets_file: "{{ playbook_dir }}/secrets.yml"
#
## full disk encryption
#vm_fde_enabled: false
#vm_fde_mode: p
#vm_fde_passphrase_length: 32
#
## OpenBSD specific 
#vm_os: OpenBSD
#vm_os_version: 7.5
#vm_os_arch: amd64
#
## netboot config
#netboot_host: netboot.rstms.net
#netboot_iso: http://{{ netboot_host }}/rstms-netboot.iso
#netboot_dir: /var/www/netboot
#netboot_gui: false
#netboot_fullscreen: true
#netboot_timeout: 300
#netboot_packages: ["py3-pip"]
#
## autoinstall config
#install_host: install.rstms.net
#install_config_dir: /var/www/htdocs
