vm_hostname: "{{ inventory_hostname.split('.')[0] }}"
vm_username: "{{ lookup('env', 'USER') }}"
vm_password: "{{ ansible_become_password }}"
vm_sshd_enabled: true
vm_ssh_public_key: "{{ lookup('file', lookup('env', 'HOME') ~ '/.ssh/id_ed25519.pub') }}"
vm_timezone: "{{ lookup('pipe', 'date +%Z') }}"
vm_cpu_count: 1
vm_disk_mb: 8192
vm_ram_mb: 1024
vm_headless: true
vm_password_length: 8
vm_filesystem_dir: ""

vm_secrets_file: ""
vm_rootdisk_device: "nvme0n1"

# full disk encryption
vm_fde_enabled: false
vm_fde_mode: p
vm_fde_passphrase_length: 32

# OpenBSD specific 
vm_os: OpenBSD
vm_os_version: 7.5
vm_os_arch: amd64

# netboot config
netboot_host: netboot.rstms.net
netboot_iso: https://{{ netboot_host }}/iso/ipxe.iso
netboot_dir: /var/www/netboot
netboot_proxy: ""
netboot_gui: false
netboot_fullscreen: false
netboot_timeout: 600
netboot_wait: true
netboot_keep_startup_scripts: false
netboot_install_x11_packages: true
netboot_remove_systemd: true

# packages added by default
netboot_auto_packages:
  debian:
    - doas
    - sudo
    - rsyslog
    - python3-pip
  openbsd:
    - py3-pip
  alpine:
    - doas

# packages added at first boot
netboot_packages: []

# command run at first boot
netboot_command: ""
