
- name: create instance
  command: vmctl create --cpu {{ vm_cpu_count }} --ram {{ vm_ram_mb }} --disk {{ vm_disk_mb }} {{ vm_hostname }} --guest-timezone UTC
  register: result
  delegate_to: localhost
  vars:
    ansible_connection: local

- name: init instance_info
  set_fact:
    instance_info: "{{ instance_info | combine(result.stdout | from_json) | combine({'created': true, 'exists': true}) }}"

- name: install and configure
  include_tasks: install.yml
  vars:
    os_name: "{{ vm_os | lower }}"
