
- name: Set install_package_path
  set_fact:
    install_package_path: "{{ vm_os | lower }}/install"

- name: set install_package_dir
  set_fact:
    install_package_dir: "{{ netboot_dir }}/{{ install_package_path }}"

- name: Set install_package_filename
  set_fact:
    install_package_filename: "{{ instance_info.mac }}-{{ vm_hostname }}.tgz"

- name: Add openssh-server to debian netboot_auto_packages
  set_fact:
    netboot_auto_packages: "{{ netboot_auto_packages | combine({ 'debian': (netboot_auto_packages.debian + ['openssh-server']) }) }}"
  when: vm_sshd_enabled

- name: Remove systemd 
  set_fact:
    netboot_auto_packages: "{{ netboot_auto_packages | combine({ 'debian': (['sysvinit-core', 'libpam-elogind'] + netboot_auto_packages.debian) }) }}"
  when: netboot_remove_systemd

- name: Verify disk encryption passphrase
  assert:
    that:
      - vm_fde_passphrase is defined
      - vm_fde_password | length > vm_fde_passphrase_minimum_length
    fail_msg: "vm_fde_passphrase must be provided as a vaulted variable"
  when: vm_fde_enabled and (vm_fde_mode == 'p')

- name: Hash user password 
  command:
    cmd: openssl passwd -6 -stdin
    stdin: "{{ vm_password }}"
  register: user_password_hash
  delegate_to: localhost
  vars:
    ansible_connection: local
  become: false

- name: Generate root password
  include_tasks: generate_password.yml
  vars:
    label: "{{ vm_hostname }}_root"
    length: "{{ vm_password_length }}"
    vault_file: "{{ vm_secrets_file }}"

- name: Hash root password
  command: 
    cmd: openssl passwd -6 -stdin
    stdin: "{{ generated_password.stdout | trim }}"
  register: root_password_hash
  delegate_to: localhost
  vars:
    ansible_connection: local
  become: false

- name: Generate FDE password
  include_tasks: generate_password.yml
  vars:
    label: "{{ vm_hostname }}_disk"
    length: "{{ vm_fde_password_length }}"
    vault_file: "{{ vm_secrets_file }}"
  when: vm_fde_enabled

- name: Upload autoinstall config file
  template:
    src: debian_preseed.j2
    dest: "{{ netboot_dir }}/{{ instance_info.mac }}-preseed.conf"
    owner: root
    group: www
    mode: '0644'
    force: true

# User may add firstboot commands by including /install.site in the vm_filesystem_dir tree
# The debian firstboot script will execute /install.site if it is present
# The variable is set "" so the OpenBSD auto-gen logic will be skipped
- name: Create and upload site_package tarball
  include_tasks: "upload_site_package.yml"
  vars:
    firstboot_template: "debian_firstboot"
    install_dot_site: ""

- name: Reload httpd
  command: rcctl reload httpd
