
- name: Configure netboot
  include_tasks:
    file: netboot_config.yml
    apply: 
      delegate_to: "{{ netboot_host }}"
      become: true
      become_method: doas

- name: Configure OS autoinstall
  include_tasks:
    file: "{{ vm_os | lower }}_autoinstall_config.yml"
    apply: 
      delegate_to: "{{ netboot_host }}"
      become: true
      become_method: doas

- name: Start netboot installation
  command: "vmctl start --iso {{ netboot_iso }} --connect {{ '--fullscreen ' if netboot_fullscreen else ''}} {{ '--gui ' if netboot_gui else ''}}{{ vm_hostname }}"
  delegate_to: localhost
  vars:
    ansible_connection: local

- name: Wait for netboot installation complete
  include_tasks:
    file: netboot_wait.yml
    apply: 
      delegate_to: "{{ netboot_host }}"
      become: true
      become_method: doas

- name: Cleanup OS autoinstall
  include_tasks:
    file: "{{ vm_os | lower }}_autoinstall_cleanup.yml"
    apply:
      delegate_to: "{{ netboot_host }}"
      become: true
      become_method: doas

- name: Cleanup netboot
  include_tasks:
    file: netboot_cleanup.yml
    apply: 
      delegate_to: "{{ netboot_host }}"
      become: true
      become_method: doas
