- name: Remove current host keys from known_hosts
  command: ssh-keygen -R {{ vm_hostname }} -f {{ home }}/.ssh/known_hosts

- name: Update known_hosts with new host keys
  shell: ssh-keyscan {{ vm_hostname }} >> {{ home }}/.ssh/known_hosts
  when: state == 'present'
