
- name: Remove host keys from known_hosts for current hostname
  command: ssh-keygen -R {{ vm_hostname }} -f {{ home }}/.ssh/known_hosts
  delegate_to: localhost
  vars:
    ansible_connection: local

- name: Remove host keys from known_hosts for current IP
  command: ssh-keygen -R {{ ip }} -f {{ home }}/.ssh/known_hosts
  delegate_to: localhost
  vars:
    ansible_connection: local
  when: ip | default("") | length > 0

- name: Update known_hosts with new host keys
  shell: ssh-keyscan {{ vm_hostname }} >> {{ home }}/.ssh/known_hosts
  delegate_to: localhost
  vars:
    ansible_connection: local
  when: state == 'present'
