
- name: Create temp directory for building site package
  command: mktemp -d
  register: result

- name: set package_build_dir
  set_fact:
    package_build_dir: "{{ result.stdout | trim }}"

- name: Copy vm_filesystem_dir files to site package 
  copy: 
    src: "{{ vm_filesystem_dir }}/"
    dest: "{{ package_build_dir }}"
    owner: root
    group: wheel
    mode: preserve
  when: vm_filesystem_dir | length > 0

- name: Ensure /etc directory exists in site package
  file:
    path: "{{ package_build_dir }}/etc"
    state: "directory"
    mode: "0755"
    owner: "root"
    group: "wheel"
  when: firstboot_template | default("") | length > 0

- name: write install.site
  include_tasks: write_install_dot_site.yml

- name: check site package for clobbered files
  include_tasks:
    file: check_site_package_clobbers.yml
  loop:
    - etc/rc.firsttime
    - etc/rc.firsttime.user

# on openbsd, /etc/rc.firsttime is written during execution of install.site
# on debian, /etc/rc.firsttime is written here
- name: Write firstboot script to /etc/rc.firsttime
  template:
    src: debian_rc_firsttime.j2
    dest: "{{ package_build_dir }}/etc/rc.firsttime"
    mode: "0700"
    owner: root
    group: wheel
    force: yes
  when: vm_os | lower == 'debian'

- name: Write netboot_command to /etc/rc.firsttime.user
  copy:
    content: "{{ '#!/bin/sh\n' ~ netboot_command ~ '\n' }}"
    dest: "{{ package_build_dir }}/etc/rc.firsttime.user"
    mode: "0700"
    owner: root
    group: wheel
    force: yes
  when: netboot_command | default("") | length > 0

- name: Generate site package tarball
  command:
    cmd: "tar -czvhf {{ install_package_dir }}/{{ install_package_filename }} ."
    chdir: "{{ package_build_dir }}"

#- name: debugging fetch package tarball
#  fetch: 
#    src: "{{ install_package_dir }}/{{ install_package_filename }}"
#    dest: "{{ playbook_dir }}/"
#    flat: true

- name: Cleanup temp directory
  file:
    path: "{{ package_build_dir }}"
    state: absent

- name: Set site package tarball permissions
  file: 
    path: "{{ install_package_dir }}/{{ install_package_filename }}"
    owner: root
    group: www
    mode: "0644"

- name: Rewrite package index
  shell:
    cmd: "ls -lT >index.txt"
    chdir: "{{ install_package_dir }}"

