
- name: Check for install.site in install_filesystem
  stat: 
    path: "{{ package_build_dir }}/install.site"
  register: uploaded_install_site

- name: Read uploaded package install.site content
  slurp:
    path: "{{ package_build_dir }}/install.site"
  when: uploaded_install_site.stat.exists
  register: install_site_commands

- name: Write system install.site header
  template:
    src: "{{ vm_os | lower }}_install.site.j2"
    dest: "{{ package_build_dir }}/install.site"
    mode: "0700"
    owner: root
    group: wheel

- name: Append package install.site content
  lineinfile:
    path: "{{ package_build_dir }}/install.site"
    line: "{{ install_site_commands.content | b64decode }}"
    state: present
  when: uploaded_install_site.stat.exists
