argument_specs:
  workstation_instance:
    short_description: vmware workstation instance management role
    description:
      - Create or Destroy a VM instance based on the valueo of the `vm_state` variable.
        Note that when creating, one must set `gather_facts: no` since the instance will
        not exist at the start of the play.
      - When an instance is created, it boots from a netboot ISO downloaded from
        the netboot server which references an IPXE script for the specified OS.
      - Additionally, an autoconfig response file is generated along with an initial
        package tarball.  A filesystem tree may be loaded into this package which will
        be untarred into the root directory of the target system before the initial boot.
      - The role waits for the installation to report completion (or a timeout) then
        cleans up the generated config files on the netboot and autoinstall servers.
    author:
      - Matt Krueger <mkrueger@rstms.net>
    options:
      vm_state:
        type: "str"
        required: false
        default: "present"
        description: 
          - "Create or Destroy a VM instance"
          - "present - create, configure, and netboot an instance and wait for installation"
          - "absent - destroy an instance"
      vm_hostname:
        type: "str"
        required: false
        default: "inventory_hostname_short"
        description: "instance name"
      vm_username:
        type: "str"
        required: false
        default: "value of `ansible_user`"
        description: "username created on instance during configuration"
      vm_password:
        type: "str"
        required: false
        default: "value of `ansible_become_password`"
        description: "password used when creating vm_username account"
      vm_sshd_enabled:
        type: "bool"
        required: false
        default: true
        description: "enable sshd during instance configuration"
      vm_ssh_public_key:
        type: "str"
        required: false
        default: "`ansible_user` ~/.ssh/id_ed25519.pub"
        description: "public key written to target's `~/.ssh/authorized_hosts`"

      vm_timezone:
        type: "str"
        required: false
        default: "(timezone of control system)"

      vm_cpu_count:
        type: "int"
        required: false
        default: 1
        description: VM CPU allocation

      vm_disk_mb:
        type: "int"
        required: false
        default: 8192
        description: Virtual Disk size in MB
    
      vm_ram_mb:
        type: "int"
        required: false
        default: 1024
        description: VM RAM allocation in MB

      vm_headless:
        type: "bool"
        required: false
        default: true
        description: selects guest OS installation of X desktop

      vm_password_length:
        type: "int"
        required: false
        default: 32
        description: length of auto-generated root password
    
      vm_filesystem_dir:
        type: "str"
        required: false
        default: ""
        description: optional directory for inclusion in site install package

      vm_update_known_hosts:
        type: "bool"
        required: false
        default: true
        description: "modify local ~/.ssh/known_hosts on VM create/destroy"

      vm_secrets_file: 
        type: "str"
        required: false
        default: false
        description: "local filename for writing autogenerated root password with ansible-vault"

## full disk encryption
#vm_fde_enabled: false
#vm_fde_mode: p
#vm_fde_passphrase_length: 32
#
## OpenBSD specific 
#vm_os: OpenBSD
#vm_os_version: 7.5
#vm_os_arch: amd64
#
## netboot config
#netboot_host: netboot.rstms.net
#netboot_iso: http://{{ netboot_host }}/rstms-netboot.iso
#netboot_dir: /var/www/netboot
#netboot_gui: false
#netboot_fullscreen: true
#netboot_timeout: 300
#netboot_packages: ["py3-pip"]
#
## autoinstall config
#install_host: install.rstms.net
#install_config_dir: /var/www/htdocs
