
- name: Remove host keys from known_hosts
  include_tasks:
    file: update_known_hosts.yml
    apply:
      delegate_to: localhost
  vars:
    hostname: "{{ vm_hostname }}"
    home: "{{ lookup('env', 'HOME') }}"
    state: absent
  when: vm_update_known_hosts

- name: destroy instance
  command: vmctl destroy --force {{ vm_hostname }}
  register: result
  delegate_to: localhost

- name: init instance_info
  set_fact:
    instance_info: "{{ instance_info | combine(result.stdout | from_json) }}"

- name: set destroyed  
  set_fact:
      instance_info: "{{ instance_info | combine({'destroyed': true, 'exists': false}) }}"
